name: Postman API Tests

on:
  push:
  workflow_dispatch:

jobs:
  newman-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run collection.json
