name: Postman CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run "https://api.getpostman.com/collections/47182651-9d3fc9bc-db8f-43c4-89dc-7f80f074c879?apikey=${{ secrets.POSTMAN_API_KEY }}"
